# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e72f86ce859ce15e1b2a244eaa7c76b802ea8ecaaae37d2752bc51eee27c6bba438187bc0ab619036df65baf19d8201a2e974b4375441f6b1628154bddbffc6

test:
  secret_key_base: e4aed4b4879e47a5713b43981052b73071823b312b381d95e3156e9e9715e80109354defb8dab2c03e3c916fc905ee63f2187b43f36dafca78a09235788cf3ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
